#!/usr/bin/env sh

result=${1:?Please specify result directory}

QEMU_NET_OPTS=hostfwd=tcp::9922-:22
QEMU_OPTS="-m 2G"
export QEMU_NET_OPTS QEMU_OPTS

$result/bin/run-nixvm-vm &
sleep 1
echo "use 'ssh -p9922 localhost' to connect to the vm"
